### ISSUE TITLE
Test ArraySerializable

### ISSUE THREAD

**Issue by halfpastfouram** [halfpastfouram/PHPChartJS#15]
Write unit tests for:

- [ ] - \Halfpastfouram\PHPChartJS\Delegate\ArraySerializable
- [ ] - \Halfpastfouram\PHPChartJS\ArraySerializableInterface

**Comment by gbonnema** [comment]
Change reflection to walk the hierarchy tree (bottom to top) gathering attributes from top to bottom to enable subclass overrides to effectively override the value of the superclass.

**Comment by gbonnema** [comment]
Modifications to  ArraySerializable addressed. See also #32,
