### ISSUE TITLE
Trait ArraySerializable calls getArrayCopy on external objects

### ISSUE THREAD

**Issue by gbonnema** [halfpastfouram/PHPChartJS#41]
Classes that contain expressions use the Zend\Json\Expr object to store the expression (and using jsonSerialize to create a javascript expression). However, Zend\Json\Expr does not contain any getArrayCopy while ArraySerializable attempts to call it.

Solution is to use reflection the check the presence of getArrayCopy.

**Comment by halfpastfouram** [comment]
This issue has been fixed but that fix results in problems elsewhere.
