### ISSUE TITLE
Example bar.php no longer works

### ISSUE THREAD

**Issue by gbonnema** [halfpastfouram/PHPChartJS#44]
The example source for bar does not work. It shows an empty page.

**Comment by halfpastfouram** [comment]
What commit is responsible for fixing this issue?

**Comment by halfpastfouram** [comment]
The following commit was responsible for fixing the issue. Also, the ticket shouldn't have been closed yet. https://github.com/halfpastfouram/PHPChartJS/commit/9a5c178a62446cf67259e0da5ddbb0df0d1e8387

**Comment by gbonnema** [comment]
This is only an issue in dev and is solved in dev.
