### ISSUE TITLE
Add dataset to a chart changes the owner

### ISSUE THREAD

**Issue by gbonnema** [halfpastfouram/PHPChartJS#46]
When a user currently adds a dataset to a chart, the user cannot use *the same* dataset for a different chart. The reason is that when adding a dataset to a chart, the chart changes the owner in the dataset to itself. If the user *would* share the dataset between charts, then the last chart that has the dataset added becomes the owner of the dataset. The result is undefined.

`$dataSet = new DataSet; /* Then add some data to dataset */`
`$chart1->addDataSet($dataSet);`
`$chart2->addDataSet($dataSet);`

This code will lead to `$dataSet` being owned by `$chart2`. The results for `$chart1` are undefined.

The questions are:
1. Documentation necessary?
2. Preventive action necessary? F.i. preventing the add if the dataset already has an owner
3. Making the add independent of the object. F.i. add by value using a clone of the object.

**Comment by halfpastfouram** [comment]
You have a point but I don't think this should be an issue. We can't build in safety guards to keep every developer safe. Common sense is expected in this case. Want to add a data set to two different charts? Cloning is the way.
