### ISSUE TITLE
LineDataSet: 'fill' not working

### ISSUE THREAD

**Issue by artggd** [halfpastfouram/PHPChartJS#52]
Hi,

The fill attribute of LineDataSet seems to have no effect on the generated code. This is due to its PHPDoc var type being `bool|string` and the type comparison in [ArraySerializable](https://github.com/halfpastfouram/PHPChartJS/blob/master/src/Delegate/ArraySerializable.php#L39) only working for `bool` or `boolean`

Coming-up with a PR soon.

**Comment by halfpastfouram** [comment]
You seem to have a good point there. I'm looking forward to your PR.

**Comment by artggd** [comment]
You can review my PR here => #53 😊

**Comment by halfpastfouram** [comment]
Fixed f5d9002cec55b2459f224860f71bb35cf0d42319 and e69d8b336076e11ddbb334ea0b23227dcda86b76
