### ISSUE TITLE
Please add release version 1.0.0

### ISSUE THREAD

**Issue by Tastaturberuf** [halfpastfouram/PHPChartJS#55]
Thansk for your great work!

I can't use the library because the root-composer allows no "dev-master" versions. You can make a release 1.0.0 and all works perfect.

https://github.com/composer/composer/issues/1478

**Comment by Tastaturberuf** [comment]
ups. I see there is a release 1.0.0

i must dig deeper why this not works for me. sorry.

**Comment by Tastaturberuf** [comment]
packagist.org is not in sync with this repository! Thats why the requirement ```~1.0``` don't work. Pls sync the repository with packagist.

**Comment by halfpastfouram** [comment]
Thanks for telling me about this. This should be fixed now in v1.0.1.

**Comment by Tastaturberuf** [comment]
works like a charme. thanks 🥇
