### ISSUE TITLE
Install instructions for newbies

### ISSUE THREAD

**Issue by martinmagnusson** [halfpastfouram/PHPChartJS#70]
I cannot manage to install and use phpchartjs properly. I have no experience with compose, which might be part of the explanation, but could you please add more newbie-friendly step-by-step instructions?

I did `sudo composer require halfpastfouram/phpchartjs` and moved the newly created `vendor` directory to `/var/www/html`. I entered the `vendor/halfpastfouram/phpchartjs` and did `sudo composer install`. 

Still, using the demo php file in the instructions only gives me a blank page. I added `?>` at the end, but that did not fix it. I added `ini_set('display_errors',1);` for debugging, and then I get "Fatal error: Uncaught Error: Class 'Halfpastfour\PHPChartJS\Chart\Bar' not found in /var/www/html/phpchartjs.php:8 Stack trace: #0 {main} thrown in /var/www/html/phpchartjs.php on line 8"

What else could be missing, or where could I start troubleshooting?

**Comment by halfpastfouram** [comment]
You usually leave everything in the vendor directory where it is and require the composer autoloader in your project like so:

```
<?php
require 'path/to/vendor/autoload.php';
```

You can then use any of the classes you installed with composer. You can find composer's basic usage guide over here: https://getcomposer.org/doc/01-basic-usage.md
